# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_res50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: 'D:/ait102/python/FaceID_Project/data/archive/lfw-deepfunneled/lfw-deepfunneled'
binary_img: Flase
num_classes: 5749
num_samples: 13233
epochs: 5
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: 'D:/ait102/python/FaceID_Project/data/archive/lfw-deepfunneled/lfw-deepfunneled'